name: CI/CD for ChatTW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --env MONGO_INITDB_ROOT_USERNAME=example
          --env MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
          - mongo-data:/data/db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python tests
        run: |
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          cd web
          npm install

      - name: Run Next.js tests
        run: |
          cd web
          npm run test

