name: CI/CD for ChatTW

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          cd ai
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python tests
        run: |
          cd ai/tests
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          cd web
          npm install

      - name: Run Next.js tests
        run: |
          cd web
          npm run test

