name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./web

      - name: Run Node.js Tests
        run: |
          npm run test || { echo 'Node.js Tests Failed'; exit 1; }
        working-directory: ./web

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./ai/requirements.txt

      - name: Run Python Tests
        run: |
          pytest ./ai
